stages:
  - lint
  - build

default:
  cache:
    - key:
        files:
          - pixi.lock
      paths:
        - .pixi/

lint-job:
  stage: lint
  image: ghcr.io/prefix-dev/pixi:0.24.2
  script:
    - pixi run lint

build-job:
  stage: build
  artifacts:
    name: presentation
    expose_as: presentation.pdf
    paths:
      - presentation.pdf
  image: ghcr.io/prefix-dev/pixi:0.24.2
  script:
    - pixi run compile
